/aruco_detect:
  ros__parameters:
    marker_size: 0.1
    aruco_dictionary_id: DICT_6X6_1000
    image_topic: /zed/image_raw
    camera_info_topic: /zed/camera_info
    camera_frame: zed_camera_link
    aruco_ids: [25]