/traj_pred:
  ros__parameters:
    x_limits: [0.0, 1.0]
    y_limits: [-1.0, 1.0]
    z_limits: [0.0, 0.2]
    N: 7
    N_best: 4
    v_gate: 10
    window_size: 15
    gate_residual_thresh: 0.2
    min_inliers_for_gate: 5
    actual_marker_topic: /ball_actual
    pred_marker_topic: /ball_pred